Repository fsoco/fsoco-dataset, pull requests merged in 2020-11, with the labels that each got.

#73 Docs/#72 add epfl racing team
  docs/README.md
  docs/_includes/overview_stats.html
  docs/_includes/stats_for_nerds_bokeh.slides.html
  docs/assets/img/teams/epfl_racing.png
  docs/assets/img/teams/raw/epfl_racing.png
  docs/pages/contributors.md
Labels: contributor

#75 Add automatic generation of global cosine sim table
  docs/_includes/stats_for_nerds_bokeh.slides.html
  docs/assets/stats_for_nerds.ipynb
Labels: bug

#77 Add IIT Bombay Racing
  docs/README.md
  docs/_includes/overview_stats.html
  docs/_includes/stats_for_nerds_bokeh.slides.html
  docs/assets/img/teams/iit_bombay_racing.png
  docs/assets/img/teams/raw/iit_bombay_racing.png
  docs/assets/stats_for_nerds.ipynb
  docs/pages/contributors.md
Labels: contributor

#80 Add Aristurtle
  docs/README.md
  docs/_includes/overview_stats.html
  docs/_includes/stats_for_nerds_bokeh.slides.html
  docs/assets/img/teams/aristurtle.png
  docs/assets/img/teams/raw/aristurtle.png
  docs/pages/contributors.md
Labels: contributor

#67 #66 refactoring of label converters and addition of sly2voc
  tools/label_converters/label_converters.py
  tools/label_converters/sly2voc/__init__.py
  tools/label_converters/sly2voc/click_sly2voc.py
  tools/label_converters/sly2voc/sly2voc.py
  tools/label_converters/yolo2sly/yolo2sly.py
Labels: enhancement

#83 Enable search engine crawlers
  docs/assets/img/thumbnails/desk-messy.jpeg
  docs/assets/img/thumbnails/desk-messy.jpg
  docs/assets/img/thumbnails/desk-messy.webp
  docs/robots.txt
Labels: bug

#81 Parallelize statistics collector and use cache on Colab
  tools/click_fsoco.py
  tools/collect_stats/click_collect_stats.py
  tools/collect_stats/stats_collector.py
  tools/setup.py
  tools/similarity_scorer/click_similarity_scorer.py
  tools/similarity_scorer/similarity_scorer.py
  tools/similarity_scorer/utils/feature_extractor.py
Labels: enhancement
