Repository fsoco/fsoco-dataset, pull requests merged in 2020-09, with the labels that each got.

#32 Docs/#19 remove betatest note
  docs/pages/contact_us.md
  docs/pages/labeling_guidelines.md
Labels: documentation

#41 Tools/#39 Extend stats collector to include tags
  tools/collect_stats/stats_collector.py
Labels: tools

#37 Docs/#19 rename to instance segmentation
  docs/pages/examples.md
  docs/pages/how_to_contribute.md
  docs/pages/overview.md
  docs/pages/tools.md
Labels: documentation

#42 Update link to contributing file
  docs/README.md
Labels: documentation

#45 Bug fix/#43 update fsoco tools installation
  docs/pages/tools.md
  tools/README.md
  tools/collect_stats/stats_collector.py
  tools/setup.py
Labels: bug

#47 Add CI for FSOCO tools
  .github/workflows/tools_installation.yml
Labels: enhancement

#49 Autorun FSOCO tools CI
  .github/workflows/tools_installation.yml
Labels: enhancement

#58 Adapt template to show up in template chooser
  .github/ISSUE_TEMPLATE/new_team.md
Labels: documentation
