Repository fsoco/fsoco-dataset, pull requests merged in 2020-10, with the labels that each got.

#55 Docs/#52 extend automatic stats update
  docs/README.md
  docs/_includes/dataset_stats_badges.html
  docs/_includes/overview_stats.html
  docs/_scripts/ipynb2stats_page.sh
  docs/_scripts/requirements.txt
  docs/_scripts/update_page_stats.py
  docs/pages/overview.md
Labels: documentation

#65 Add the Racetech Racing Team
  docs/README.md
  docs/_includes/overview_stats.html
  docs/_includes/stats_for_nerds_bokeh.slides.html
  docs/assets/img/teams/racetech.png
  docs/assets/img/teams/raw/racetech.png
  docs/pages/contributors.md
Labels: contributor

#54 Add automatic selection of best images
  docs/pages/image_similarity_score.md
  tools/similarity_scorer/click_similarity_scorer.py
  tools/similarity_scorer/similarity_scorer.py
  tools/similarity_scorer/utils/feature_extractor.py
  tools/similarity_scorer/utils/logger.py
  tools/similarity_scorer/utils/similarity_clustering.py
  tools/watermark/click_watermark.py
Labels: enhancement

#64 Pin nbconvert and missing reqs
  docs/README.md
  docs/_scripts/requirements.txt
  docs/_scripts/update_page_stats.py
Labels: bug

#71 Docs/#70 add tu wien racing
  docs/README.md
  docs/_includes/overview_stats.html
  docs/_includes/stats_for_nerds_bokeh.slides.html
  docs/assets/img/teams/raw/tu_wien_racing.png
  docs/assets/img/teams/tu_wien_racing.png
  docs/pages/contributors.md
Labels: contributor
