Repository fsoco/fsoco-dataset, pull requests merged in 2020-07, with the labels that each got.

#3 Extend readme information for GH
  docs/README.md
Labels: documentation

#4 Fix broken links and other website issues
  docs/Gemfile
  docs/_config.yml
  docs/_includes/stats_for_nerds_bokeh.slides.html
  docs/index.md
  docs/pages/examples.md
  docs/pages/faq.md
  docs/pages/how_to_contribute.md
  docs/pages/image_similarity_score.md
  docs/pages/labeling_guidelines.md
  docs/pages/overview.md
  docs/pages/tools.md
  docs/robots.txt
  tools/CONTRIBUTING.md
Labels: bug

#11 Add all contributors table
  docs/README.md
  tools/CONTRIBUTING.md
Labels: documentation

#9 Add imprint and privacy policy
  docs/_includes/footer.html
  docs/_sass/includes/_footer.scss
  docs/pages/imprint.md
  docs/pages/privacy_policy.md
Labels: documentation

#12 Improve codacy code quality grading to A
  docs/README.md
  docs/_data/social.yml
  docs/pages/how_to_contribute.md
  tools/click_fsoco.py
  tools/collect_stats/click_collect_stats.py
  tools/collect_stats/stats_collector.py
  tools/label_converters/helpers.py
  tools/label_converters/label_converters.py
  tools/label_converters/labelbox2sly/click_labelbox2sly.py
  tools/label_converters/labelbox2sly/labelbox2sly.py
  tools/label_converters/yolo2sly/click_yolo2sly.py
  tools/label_converters/yolo2sly/yolo2sly.py
  tools/similarity_scorer/metrics/cosine_metric.py
  tools/similarity_scorer/similarity_scorer.py
  tools/similarity_scorer/utils/cache.py
  tools/similarity_scorer/utils/feature_extractor.py
  tools/similarity_scorer/utils/logger.py
  tools/similarity_scorer/utils/similarity_clustering.py
  tools/watermark/click_watermark.py
  tools/watermark/watermark.py
Labels: enhancement

#18 Adjust nav list generation
  docs/_includes/footer.html
Labels: documentation

#21 Correct form submission relative links to public fsoco website
  docs/_includes/contact_form.html
  docs/_includes/contribution_form.html
Labels: documentation
