Repository fsoco/fsoco-dataset, pull requests merged in 2021-01, with the labels that each got.

#116 Bug fix/#109 statistics do not count images without labels
  docs/README.md
  docs/_includes/overview_stats.html
  docs/_includes/stats_for_nerds_bokeh.slides.html
  docs/_scripts/ipynb2stats_page.sh
  docs/_scripts/update_page_stats.py
  docs/assets/stats_for_nerds.ipynb
Labels: bug, documentation

#120 Add Einstein Motorsport
  docs/README.md
  docs/_includes/overview_stats.html
  docs/_includes/stats_for_nerds_bokeh.slides.html
  docs/assets/img/teams/einstein_motorsport.png
  docs/assets/img/teams/raw/einstein_motorsport.png
  docs/pages/contributors.md
Labels: contributor

#125 Bug fix/#124 website checks workflow
  .github/workflows/website_checks.yaml
  docs/_tests/test_contribution_procedure_status_page.py
Labels: bug

#127 Remove bitmap labels within the watermark
  tools/sanity_checker/click_sanity_checker.py
  tools/sanity_checker/label_checker.py
  tools/sanity_checker/segmentation_checker.py
Labels: tools

#126 White-/blacklist projects
  docs/_scripts/prepare_slides_html.py
  docs/_scripts/update_page_stats.py
  tools/label_converters/sly2voc/sly2voc.py
  tools/label_converters/sly2yolo/sly2yolo.py
  tools/sanity_checker/click_sanity_checker.py
  tools/sanity_checker/sanity_checker.py
Labels: tools

#128 Docs/#123 remove hard coded filtering of project names
  .github/workflows/website_checks.yaml
  .pre-commit-config.yaml
  docs/_tests/test_contribution_procedure_status_page.py
Labels: documentation

#129 [Sanity checker] Skip bounding box check for truncated cones
  tools/sanity_checker/bounding_box_checker.py
  tools/sanity_checker/label_checker.py
Labels: enhancement

#130 [Sanity checker] Remove illegal image tags
  tools/sanity_checker/checker.py
  tools/sanity_checker/click_sanity_checker.py
  tools/sanity_checker/image_checker.py
  tools/sanity_checker/label_checker.py
  tools/sanity_checker/sanity_checker.py
Labels: enhancement

#131 [Sanity checker] Fix is_tagged() function
  tools/sanity_checker/label_checker.py
Labels: bug

#132 [Sanity checker] Hotfix redundant counting due to Donations project
  tools/sanity_checker/sanity_checker.py
Labels: bug

#133 Docs/#118 add UG Racing
  docs/README.md
  docs/_includes/overview_stats.html
  docs/_includes/stats_for_nerds_bokeh.slides.html
  docs/assets/img/teams/raw/ug_racing.png
  docs/assets/img/teams/ug_racing.png
  docs/pages/contributors.md
Labels: contributor
